"""Self-contained HTML report.

Single-page deliverable with:
  - Executive summary metrics
  - Top SHAP features
  - SAE diagnostics (dead ratio, descriptor recovery distribution)
  - MMP design-rule table

No external dependencies in the rendered file — everything is inlined.
"""

from __future__ import annotations

import base64
import io
from dataclasses import dataclass
from pathlib import Path

from jinja2 import Template


TEMPLATE = Template(
    """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{{ title }}</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", system-ui, sans-serif;
         max-width: 960px; margin: 2rem auto; padding: 0 1rem; line-height: 1.5; color: #222; }
  h1 { border-bottom: 2px solid #444; padding-bottom: .3rem; }
  h2 { margin-top: 2rem; color: #2a4f7c; }
  table { border-collapse: collapse; width: 100%; margin: .5rem 0 1rem; }
  th, td { border: 1px solid #ddd; padding: .4rem .6rem; text-align: left; font-size: .92em; }
  th { background: #f4f6f9; }
  .metric { display: inline-block; padding: .4rem .8rem; margin: .2rem; background: #eef3fa;
            border-left: 4px solid #2a4f7c; border-radius: 3px; font-weight: 600; }
  .caveat { background: #fff8e1; border-left: 4px solid #f5a623; padding: .5rem .8rem;
            margin: 1rem 0; font-size: .92em; }
  img { max-width: 100%; border: 1px solid #eee; }
  code { background: #f5f5f5; padding: 1px 4px; border-radius: 3px; font-size: .9em; }
</style>
</head>
<body>
<h1>{{ title }}</h1>
<p><em>Generated by qsar_tutorial. Data: {{ dataset_name }} (N={{ n_total }}).</em></p>

<h2>1. Predictive performance (OOF)</h2>
<div>
  <span class="metric">AUC: {{ "%.3f"|format(metrics.AUC) }}</span>
  <span class="metric">AUPRC: {{ "%.3f"|format(metrics.AUPRC) }}</span>
  <span class="metric">MCC@0.5: {{ "%.3f"|format(metrics["MCC@0.5"]) }}</span>
</div>
<div class="caveat">
  Numbers are <strong>out-of-fold</strong> (no leakage between feature
  extraction and evaluation). Compare against your project's leaky baseline
  if any — the gap is often 0.10–0.15 AUC.
</div>

<h2>2. Top SHAP features (global)</h2>
<table><thead><tr><th>#</th><th>Feature</th><th>mean |SHAP|</th></tr></thead><tbody>
{% for name, imp in top_shap %}
<tr><td>{{ loop.index }}</td><td><code>{{ name }}</code></td><td>{{ "%.4f"|format(imp) }}</td></tr>
{% endfor %}
</tbody></table>

{% if shap_scaffold_diversity %}
<h2>2a. SHAP scaffold scope (top features)</h2>
<div class="caveat">
  For each top SHAP feature (ECFP4 path only), we count distinct Bemis-Murcko
  scaffolds among compounds where the feature is "on". Low diversity = the
  attribution may be series-bound, not a general structure–activity rule.
</div>
<table>
<thead><tr><th>Feature</th><th>n_compounds_on</th><th>n_distinct_scaffolds</th><th>scope</th></tr></thead>
<tbody>
{% for row in shap_scaffold_diversity %}
<tr>
<td><code>{{ row.feature }}</code></td>
<td>{{ row.n_compounds_on }}</td>
<td>{{ row.n_distinct_scaffolds }}</td>
<td>{% if row.scaffold_bound %}<strong>scaffold-bound</strong>{% else %}broad{% endif %}</td>
</tr>
{% endfor %}
</tbody>
</table>
{% endif %}

{% if stability_rows %}
<h2>2b. SHAP stability across {{ stability_n_folds }} folds</h2>
<div class="caveat">
  <strong>How to read.</strong> 5/5 fold-presence is strong evidence that the
  model relies on this feature consistently. 1-2/5 is likely spurious — the
  feature won the lottery in one fold's training data. We do not apply any
  threshold here; the distribution is the deliverable.
</div>
<table>
<thead><tr>
  <th>#</th><th>Feature</th><th>fold-presence</th><th>mean rank</th>
  <th>rank std</th><th>mean |SHAP|</th>
</tr></thead>
<tbody>
{% for r in stability_rows %}
<tr>
  <td>{{ loop.index }}</td>
  <td><code>{{ r.feature }}</code></td>
  <td>{{ r.fold_presence }} / {{ stability_n_folds }}</td>
  <td>{{ "%.1f"|format(r.mean_rank) }}</td>
  <td>{{ "%.1f"|format(r.rank_std) }}</td>
  <td>{{ "%.4f"|format(r.mean_importance) }}</td>
</tr>
{% endfor %}
</tbody>
</table>
{% endif %}

{% if split_comparison %}
<h2>1b. Random vs scaffold split — honest evaluation gap</h2>
<table>
<thead><tr><th>Split</th><th>AUC</th><th>AUPRC</th><th>MCC@0.5</th><th>fold std (AUC)</th></tr></thead>
<tbody>
{% for row in split_comparison %}
<tr>
  <td>{{ row.split }}</td>
  <td>{{ "%.3f"|format(row.AUC) }}</td>
  <td>{{ "%.3f"|format(row.AUPRC) }}</td>
  <td>{{ "%.3f"|format(row["MCC@0.5"]) }}</td>
  <td>{{ "%.3f"|format(row.fold_auc_std) }}</td>
</tr>
{% endfor %}
</tbody>
</table>
<div class="caveat">
  <strong>Reading.</strong> Scaffold-split AUC is the honest estimate of
  generalization to new chemistry. Random-split AUC inflates because close
  analogues leak between train and validation. The gap (random − scaffold)
  measures how much of the headline number is leakage. Gap is reported
  regardless of size — that is the honest framing.
</div>
{% endif %}

<h2>3. SAE diagnostics</h2>
<p>
  <span class="metric">latent_dim: {{ sae.latent_dim }}</span>
  <span class="metric">dead_ratio: {{ "%.3f"|format(sae.dead_ratio) }}</span>
  <span class="metric">descriptor R² median: {{ "%.3f"|format(sae.r2_median) }}</span>
  <span class="metric">descriptors R²&gt;0.5: {{ sae.r2_above_05 }} / {{ sae.r2_total }}</span>
</p>
<div class="caveat">
  Healthy SAE: dead_ratio &lt; 0.05 AND descriptor R² median &gt; 0.5.
  Otherwise re-train with stronger normalization or different L1 lambda.
</div>

<h2>4. MMP design-rule candidates</h2>
<table>
<thead>
<tr>
<th>Transformation</th>
<th>n_applied</th>
<th>Δp(active) mean</th>
<th>95% CI</th>
<th>Exemplar Δp</th>
<th>n_scaffolds</th>
<th>scope</th>
</tr>
</thead>
<tbody>
{% for r in mmp_rows %}
<tr>
<td><code>{{ r.name }}</code></td>
<td>{{ r.n_applied }}</td>
<td>{{ "%.3f"|format(r.delta_p_mean) }}</td>
<td>[{{ "%.3f"|format(r.delta_p_ci95[0]) }}, {{ "%.3f"|format(r.delta_p_ci95[1]) }}]</td>
<td>{{ "%.3f"|format(r.exemplar_delta) }}</td>
<td>{{ r.get("n_distinct_scaffolds", "—") }}</td>
<td>{% if r.get("is_series_local") %}<strong>series-local</strong>{% else %}cross-series{% endif %}</td>
</tr>
{% endfor %}
</tbody>
</table>
<div class="caveat">
  <strong>Hypothesis-generating only.</strong> A 95% CI excluding 0 is necessary
  but not sufficient. Promotion to "validated rule" requires wet-lab confirmation
  with n ≥ 10 analogues. See docs/BACKGROUND.md §5.3.
  <br><strong>Scope column:</strong> a rule observed on fewer than 3 distinct
  Murcko scaffolds is flagged <code>series-local</code>; its mean Δp reflects one
  chemotype, not a general SAR principle (Auer et al. 2016, PMC5198793).
</div>

{% if time_split %}
<h2>4b. Time-split evaluation</h2>
<p>Trained on molecules with <code>document_year &le; {{ time_split.cutoff }}</code>,
evaluated on molecules with <code>document_year &gt; {{ time_split.cutoff }}</code>.
Sheridan 2013-style chronological hold-out — the practical "past predicts future" test.</p>
<table>
<thead><tr><th>n_train</th><th>n_test</th><th>train_active%</th><th>test_active%</th><th>AUC</th><th>AUPRC</th></tr></thead>
<tbody>
<tr>
<td>{{ time_split.n_train }}</td>
<td>{{ time_split.n_test }}</td>
<td>{{ "%.1f"|format(time_split.train_active_pct * 100) }}%</td>
<td>{{ "%.1f"|format(time_split.test_active_pct * 100) }}%</td>
<td>{{ "%.3f"|format(time_split.AUC) }}</td>
<td>{{ "%.3f"|format(time_split.AUPRC) }}</td>
</tr>
</tbody>
</table>
{% endif %}

{% if external %}
<h2>4c. External hold-out evaluation</h2>
<p>Final model (trained on full training set) scored on
<code>{{ external.csv }}</code> — a genuinely independent set with no
SMILES overlap with the training data.</p>
<table>
<thead><tr><th>n</th><th>active%</th><th>External AUC</th><th>AUPRC</th><th>OOF AUC</th><th>Gap</th></tr></thead>
<tbody>
<tr>
<td>{{ external.n }}</td>
<td>{{ "%.1f"|format(external.active_pct * 100) }}%</td>
<td>{{ "%.3f"|format(external.AUC) }}</td>
<td>{{ "%.3f"|format(external.AUPRC) }}</td>
<td>{{ "%.3f"|format(external.oof_auc) }}</td>
<td><strong>{{ "%.3f"|format(external.auc_gap) }}</strong> ({{ external.gap_level }})</td>
</tr>
</tbody>
</table>
{% if external.gap_level == "severe" %}
<div class="caveat" style="background:#fdecea;border-left:4px solid #d93025;">
<strong>🔴 SEVERE COVARIATE SHIFT</strong> — External AUC drop &ge; 0.20.
Model interpretations should not be reported as generalizable until the
shift is diagnosed. Likely causes: (1) external set is from a different
assay protocol, (2) training set has memorized series-bound features, or
(3) chemical-space differences exceed model coverage.
</div>
{% elif external.gap_level == "moderate" %}
<div class="caveat" style="background:#fff8e1;border-left:4px solid #f5a623;">
<strong>⚠ MODERATE COVARIATE SHIFT</strong> — External AUC drop in
[0.10, 0.20). The model partially generalizes. Report both numbers when
making claims; treat OOF AUC as an upper bound only.
</div>
{% else %}
<div class="caveat" style="background:#e6f4ea;border-left:4px solid #137333;">
<strong>✓ External AUC within tolerance</strong> — gap &lt; 0.10. Model
appears to generalize beyond the training corpus.
</div>
{% endif %}
{% endif %}

<h2>5. How to read this report</h2>
<ol>
<li><strong>Performance section</strong>: only compare across runs that share the
same OOF protocol. Within-fold AUC is not the same number.</li>
<li><strong>SHAP features</strong>: these are <em>statistical</em> attributions. A
high mean-|SHAP| means "the model relies on this feature", not "this feature
is causal".</li>
<li><strong>SAE diagnostics</strong>: dead_ratio is the canary. If it climbs above
0.2, the SAE is broken and any feature-level interpretation built on top of
it is suspect.</li>
<li><strong>MMP rules</strong>: read the CI before the mean. A wide CI (e.g.
[-0.05, +0.30]) is not a rule, it is a coincidence with a single exemplar.</li>
</ol>
</body>
</html>
"""
)


@dataclass
class ReportPayload:
    title: str
    dataset_name: str
    n_total: int
    metrics: dict[str, float]
    top_shap: list[tuple[str, float]]
    sae: dict
    mmp_rows: list[dict]
    stability_rows: list[dict] | None = None
    time_split: dict | None = None
    external: dict | None = None
    shap_scaffold_diversity: list[dict] | None = None
    stability_n_folds: int = 0
    split_comparison: list[dict] | None = None


def render_report(payload: ReportPayload, out_path: str | Path) -> Path:
    html = TEMPLATE.render(**payload.__dict__)
    p = Path(out_path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(html, encoding="utf-8")
    return p


def _fig_to_data_uri(fig) -> str:
    """Optional helper: encode a matplotlib figure as a base64 data URI."""
    buf = io.BytesIO()
    fig.savefig(buf, format="png", dpi=120, bbox_inches="tight")
    buf.seek(0)
    return "data:image/png;base64," + base64.b64encode(buf.read()).decode("ascii")
